### PR TITLE
Fix backup condition

### PR DESCRIPTION
**Pull request by vmrob**

### CODE REVIEW

**Comment by vmrob** [comment]
Very embarrassing mistake. I was wondering why my backups weren't happening as frequently as I had hoped...

**Comment by pieterlange** [comment]
Missed that one too. :+1: Thanks again :)

**Comment by vmrob** [comment]
😑 I was actually hoping you wouldn't have merged this quite yet.. I ran into another problem because I forgot to move the `git add .` just above the conditional. Backups were right on schedule, but it always thought it was failing!

**Comment by pieterlange** [comment]
I'm waking up here.. time to get some coffee.

**Comment by vmrob** [comment]
Yup. And I'm getting tired over here, so I'll try to blame it on that..

**Pull request merged**
